server:
  port: 8088
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@172.20.64.1:27017/notification_db?authSource=admin
  kafka:
    bootstrap-servers: 172.20.64.1:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
app:
  email-service:
    url: https://api.brevo.com
    api-key:
  firebase-configuration-file:
