server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: /cart
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres_db:5432/cart_db_prod}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDLAUTO:update}
    show-sql: ${SPRING_JPA_SHOWSQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect