server:
  port: 8888

app:
  api-prefix: /api/v1
  identity-service:
    url: http://localhost:8080/identity

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
        - id: cart_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/cart/**
          filters:
            - StripPrefix=2
        - id: category_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/category/**
          filters:
            - StripPrefix=2
        - id: blog_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/blog/**
          filters:
            - StripPrefix=2
        - id: customer_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/customer/**
          filters:
            - StripPrefix=2
        - id: file_service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2
        - id: notification_service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: payment_service
          uri: http://localhost:8089
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2
        - id: order_service
          uri: http://localhost:8090
          predicates:
            - Path=${app.api-prefix}/order/**
          filters:
            - StripPrefix=2