server:
  port: 8087
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:123456789@172.20.64.1:27017/file_db?authSource=admin
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
app:
  file:
    storage-dir: D:/Uploads