server:
  port: ${SERVER_PORT:8087}
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@mongodb:27017/file_db_prod?authSource=admin}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
app:
  file:
    storage-dir: ${APP_FILE_STORAGE_DIR:/uploads_prod}