server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:postgresql://172.20.64.1:5432/identity_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  kafka:
    bootstrap-servers: 172.20.64.1:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  signerKey: "qxNOdgKfw1UmyuQ68SKM+tmEVoeAUqgvr1/eg50ufWkQTizklguIDWNP3oOGv8bS"
  expirationMinutes: 1440
  expirationRefreshMinutes: 7200
  issuer: identity-service
  passwordResetTokenExpiryMinutes: 15
  otpExpiryMinutes: 5
  otpRequestCooldownMinutes: 5

app:
  cart-service:
    url: http://172.20.64.1:8083
  file-service:
    url: http://172.20.64.1:8087
  file:
    download-prefix: http://172.20.64.1:8888/api/v1/file/media/download/
    default-image: default-avatar

admin:
  username: admin
  password: admin
  role: ADMIN